### ISSUE TITLE
Write some "meta" documentation

### ISSUE THREAD

**Issue by rbarrois** [Polytechnique-org/platal2#5]
Explains:
- [ ] Where the doc is
- [ ] How to improve / build the docs
- [ ] What should and should not go to the docs
- [ ] The global development process
- [ ] The coding rules

**Comment by rbarrois** [comment]
Idea: see http://pythonhosted.org/sphinxcontrib-httpdomain/ for API documentation
